### ISSUE TITLE
problem with unshuffle.rb

### ISSUE THREAD

**Issue by lmanchon** [joshuaburkhart/bio#1]
--Hi,

using unshuffle.rb as: ruby unshuffle.rb unmapped_fastq @DE18INS652
it returns 2 empty files:

-rw-------  0 Dec  3 17:10 -unshuf_1.fastq
-rw-------  0 Dec  3 17:10 -unshuf_2.fastq

what's wrong ?

thank you --

btw this is an extract of my input file:
@DE18INS652:98:C2L0LACXX:5:1101:4389:1989
NGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCGGCTCGAAAAAAAAAAAAAAAAAAAAAAACAACAAAGCAGTG
+
#1:BBDDBFFDDF<ACGGHHIIE?EEGGEGFG:?:000?BB000?DFHC.=F

@DE18INS652:98:C2L0LACXX:5:1101:4389:1989
AGATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGTAGATGTCGGTGGTGGCCGTATCATTAAAAAAAAAAAAAAAAAGACAGAGGGAGAAGAGGGACGAGG
+
???BDFDBFDFCFF@EF@:C)::11:?F0)09BFHI8**09BF7@''(-(.-9?DFFEEEECEECCCCC###############################
@DE18INS652:98:C2L0LACXX:5:1101:4746:1987
NTATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTATTCTGCTTGAAAAAAAAAAAAAAAAAAATCACACGCGAATA
[18:59:12][dpiquemal@genotoul][~/work/CAT/index3_TTAGGC ][61 ]head -100 unmapped_index3_TTAGGC.fq
@DE18INS652:98:C2L0LACXX:5:1101:4389:1989
NGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCGGCTCGAAAAAAAAAAAAAAAAAAAAAAACAACAAAGCAGTG
+
#1:BBDDBFFDDF<ACGGHHIIE?EEGGEGFG:?:000?BB000?DFHC.=F

@DE18INS652:98:C2L0LACXX:5:1101:4389:1989
AGATCGGAAGAGCGTCGTGTAGGGAAAGGAGTGTAGATGTCGGTGGTGGCCGTATCATTAAAAAAAAAAAAAAAAAGACAGAGGGAGAAGAGGGACGAGG
+
???BDFDBFDFCFF@EF@:C)::11:?F0)09BFHI8**09BF7@''(-(.-9?DFFEEEECEECCCCC###############################
@DE18INS652:98:C2L0LACXX:5:1101:4746:1987
NTATAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTATTCTGCTTGAAAAAAAAAAAAAAAAAAATCACACGCGAATA
+
# 11BBDDDFCFAD2<EHGGGHIHFDFE@@FD?:11::DFHG990?DFGD0BB))//55'.7.).77AEAD>;?AB3;B

@DE18INS652:98:C2L0LACXX:5:1101:4746:1987
ATACAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGGGGGCGCCGTATCATTAAAAAAAAAAAAAAAAAAACAGAAGGAGCAAGGAGAGT
+
::==DDADHFFHHC<EFH3ACFF1:1?B_0090?9B__009?FGH-'-,&_)0:BDDDDEEEEDDDDDDD@@############################
@DE18INS652:98:C2L0LACXX:5:1101:11582:1972
NGCTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAAGCATCTCGTATGCTGTGTTATGCTTGAAAAAAAAAAAAAAAAAAACAACGAATGGGAG
+
#1=DAB==CDF<<@<EGECFGFGAFG@?:DD:?1:::?DGG000?BF@D8DF

@DE18INS652:98:C2L0LACXX:5:1101:11582:1972
AGCCAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATCTCGGGGGACGCCGTATCATTAAAAAAAAAAAAAAAAATAGGAAGAGCGCAGGGGAGGA
+
:=?=BDDAA?DFDE<CFH2A?C?11:BD0)099BFD/*00?0B=C-'-,',,3;BDDDDEEEDDDDDDDDDB############################
@DE18INS652:98:C2L0LACXX:5:1101:12262:1954
NACCGTTGAGTGAAGCCGGGGCGATCGTCCTGAGGGCCCGGGGCCTCTTGGGCTCAGGGCACTCGAACTTCCTGATCTTTGAATAAAGATCGGAAGAGCA
+
#4=DDADDFFDFF<2AFCGHIJIGAFFH=DC=C.;;BBFDB33,8<ACC3>A(9<+39+(+((+2<ABBCC:>@@:@CCCC>C:>:@:>AC8<829AAAC

@DE18INS652:98:C2L0LACXX:5:1101:12262:1954
TTATTCAAAGATCAGGAAGTTCGGGTGCCCGGAGCCCAAGAGGCCGGGGGCCCTCAGGACGATCGCCCCGGCTTCACTCAACGGTTAGATCGGAAGAGCG
+
B=BDFBDDHDHHHHIGHHAFHHCBFHCC?_:C@FHF0/00=BFGG'-:<@,35ADDDDDBDDDDDDDDDDDDDDCD>:>?ACDD?BBDDDDDD??B?A##
@DE18INS652:98:C2L0LACXX:5:1101:1528:2076
TCCCGGCTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCAGCTCGTATGGCGTCTTCTCCTTGAAAAAAAAAAACAAAAAAGCAAACACAC
+
@@@FB@@AF2<2<A@<C)<<CFEHI11?G00:D0BHD00?FF##########################################################
@DE18INS652:98:C2L0LACXX:5:1101:1528:2076
AGCCGGGAAGATCGGAAGAGCGTGGTGTAGGGAAAGAGTGTAGATCTGGGTGGTCGCCGTATCATTAAAAAAAAAAAAAAAAATAAAGAAATAAGGACAA
+
:1:D4)00<22CCC<AA)11101)0000099?B0?0.)//8=7C8.))/..5AADDCCB,9,9;;ADBA@>>BB9B########################
@DE18INS652:98:C2L0LACXX:5:1101:2306:2069
AGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCAGCTTGAAAAAAAAAAAAAAAAAAAAAGAAAAAGAACGACAC
+
=B?BA=@AD<CCF<AFHCGGIHIEEEHGGIFG?DD000?DD000??DHH=FF.5B(5.).7).).=?CDD>?BD0))9&09@D#################
@DE18INS652:98:C2L0LACXX:5:1101:2306:2069
AGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGATTTCGGTGGGCGAAGTATCATTAAAAAAAAAAAAAAAAAAAAAAAATGGAGAGCAGATGTCCGA
+
=:?ADDDDH@BFHGCFGC@C:@:1_1??_00?09?0__019?<FH'(-'',,;ACEEEECECDDBDBB################################
@DE18INS652:98:C2L0LACXX:5:1101:4727:2235
GCTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGCATGCCGTCTTCTGCTTGAAAAAAAAAAAAAAAAACAAGCAAGCAGTGGAG
+
?@@=B==AF@:2<<<AB??FHGFCE9:CEGC__1?0?BGDF_9_0_?@@###################################################
@DE18INS652:98:C2L0LACXX:5:1101:4727:2235
AGCAGATCGGAAGAGCGTCGTGGGGGGAAGGAGTGTAGATCTCGGAGGAGGCCGTATCATTAAAAAAAAAAAAAAAAAGGCAAGTGGAGAGAAAGAGGGG
+
=??4B222=0:;CEEA@<2@:?0)086)&++2<8<3(+++38><<&)&(+)+8<????EDEEAAAA?????#############################
@DE18INS652:98:C2L0LACXX:5:1101:5990:2176
CTAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCGGTCTTCTGCTTGAAAAAAAAAAAAACAAAAAAGGTGCGAGTGCGTG
+
?=?BBDDDH22@?<CCGCFHDFHFB:*?@G<1111001?FG9009BBGB###################################################
@DE18INS652:98:C2L0LACXX:5:1101:5990:2176
AGAGATCGGAAGAGCGTCGTGTAGGGAAAGAGTGTAGGTCTCGGTGGGGTCCGTATCATTAAAAAAAAAAAAAAAAAAGGGGAGGGGGGATGGTGGGGCG
+
===DDDADF2<CAA<EFHCEEF):C?B:00*90??00*/099?F7--'''-.9BDEEEEEEEDDDDDDDD##############################
@DE18INS652:98:C2L0LACXX:5:1101:6806:2102
GACAGATCGGAAGAGCACACCTCTGAACTCCAGTCACTTAGGAATCTCGAATGCCGTCGTCTTATTGAAAAAAAAAAAAAAAAAGAAAAAAAGAGCCTTA
+
111442+2=022@<CEECAA22AC3:C@9:D#####################################################################
@DE18INS652:98:C2L0LACXX:5:1101:6806:2102
GTCAGATCGGAAGAGCGTCGCGTTGGGAATGAGTGTAGGTCTCGGAGGGGGCCGTATCATTAAAAAAAAAAAAAAAGGCTCTTAAACCTGCTATTGAGGC
+
==?4=22AD1ADDB+A@<21)1)0008B0(00/.==/.)//>=C;''-,,,,8?????EDDEAAAA???>>005)5)+(+234>A>>>>8<4>D::>A##
@DE18INS652:98:C2L0LACXX:5:1101:7412:2222
CTTGCTGTCTTGAAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAAGGAGACAAAGAAAGAAGGAAAGGAAGGAGGGAAGATCGGAAGAGCACAC
+
@@@FFA==DCFDF<ACFGG<<CFFEFB@7111)1:10:?:88B07?DG1.8=58=.;7..7)...;@DD@>>>CB5=?B98;?A?A:@25?+0889:8<B
@DE18INS652:98:C2L0LACXX:5:1101:7412:2222
TCCCTCCTTCCTTTCCTTCTTTCTTTGTCTCCTTCCTTCCTTCCTTCCTACCTTCCTTCCTTCCTTCCTTTCAAGACAGCAAGAGATCGGAAGAGCGTCG
+
==BADB=DFCFHHHIHGH<FIH33AAF?22<AHEGC**11?CFGH0*00*00:BGHIJJIJIJGIIJIIIJJHJ7@7.7???E7@DBDDDD?BAB;?8??
@DE18INS652:98:C2L0LACXX:5:1101:8087:2157
ACAGGGAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATTCCGTCTTATGCTTGAAAAAAAAAAAAAAAAAAAAGTAGAGTCGA
+
@@@FFDDDC<AAF<AC>FGAFAF:1:D?11?0:BB000_000000?BFH)8B################################################
@DE18INS652:98:C2L0LACXX:5:1101:8087:2157
CCCTGTAGATCGGAAGAGCGTCGAGTAGGGAAAGAGGGGAGATCTGGGGTGTCGCCGTATCATTAAAAAAAAAAAAATAGACGAGAGGCGGACGCAGAGG
+
=1?BDDABFCFFHGIIII3<2A:):??C:0:DAF?B((--55CDG)..'-,,6>ABBBBBBEEEECCCCBBBBB##########################
@DE18INS652:98:C2L0LACXX:5:1101:8325:2044
TTGGCAGATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTAGTATGTCGACTTATGCTTGAAAAAAAAAAAAAAAGAAGGAAAATAGAAAG
+
@?@DD==:A+A?A<@GFCCAAC@11?C11?11:?_00:BDB99*?D?;B08=//8)/6(--()..7?EEFE@BDC3=BB#####################
@DE18INS652:98:C2L0LACXX:5:1101:8325:2044
GCCAAAGATCGGAAGAGCGTCGGGTAGGGGAAGAGTGGAGATCTCGGGGGTCGCCGTATCATTAAAAAAAAAAAAAACGTAGGAGAAAGAGAGGGGAAGC
+

> ==?AA?AB2?CCCACCA?A<?)0)0:=8)0<<AB./(..==AB=((-56,,5:==:===????????################################
> @DE18INS652:98:C2L0LACXX:5:1101:8292:2080
> TAGCCCGAGATGGGAAGAGCACACGTCTAAACTCCAGTCACGTAGGCATCTCGTAGGCAGTCTTCTGCTTGAAAAAAAAAAAAAAATAAAAGAGAGAAGA
> +
> ??=BD=0<C)++22<CEBE<2@C:::??)001::B*0000?(0).(8=))/8.5;;A7)-.7)7;@A>@A@>AAA,;????###################

**Comment by joshuaburkhart** [comment]
unshuffle.rb uses a regular expression that only matches fastq output from the Illumina HiSeq 2000 machine I use. Please try the unshuffle_universal.rb script I uploaded last night. If that's not what you need, check the (minor) changes I made, play around with http://rubular.com, and come up with a custom script.

Cheers!
